added detection of server-side errors to CLI

diff --git a/opt/cs50/help50/bin/help50 b/opt/cs50/help50/bin/help50
--- a/opt/cs50/help50/bin/help50
+++ b/opt/cs50/help50/bin/help50
@@ -19,10 +19,20 @@ fi
 
 # POST /
 echo -en "\033[33m";
-curl \
+stdout="$(
+    curl \
     --data-urlencode "cmd=${*}" \
     --data-urlencode "format=txt" \
     --data-urlencode "script=${script}" \
     --data-urlencode "username=${C9_USER}" \
-    "$APP_URL"
+    --fail \
+    "$APP_URL" \
+    2> /dev/null
+)"
+if [ $? -eq 0 ]; then
+    echo "$stdout"
+else
+    echo "Ack, there seems to be a bug in help50!"
+    echo "Please let sysadmins@cs50.harvard.edu with which error you need help!"
+fi
 echo -en "\033[39m"
